### ISSUE TITLE
Aligning representation distributions

### ISSUE THREAD

**Issue by skr998** [DanielTrosten/mvc#2]
Hello author, I have a question here. The term ‘Aligning representation distributions’ has been mentioned in your paper. Can it be understood as learning the features of different views to obtain a unified feature representation？But what is the difference between this and feature fusion?

**Comment by DanielTrosten** [comment]
Hello! "Aligning representation distributions" refers to the process of making the _distribution_ of representations (output of view-specific encoder) from one view, identical to the _distribution_ of representations from the other view. 

(Feature) fusion is when you aggregate representations from all views into a single representation, e.g. by summing or averaging.
